
Vagrant.configure("2") do |config|
  config.vm.box = "azure"

  # use local ssh key to connect to remote vagrant box
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.vm.provider :azure do |azure, override|
    azure.location = "westus"

    azure.vm_vhd_uri = "https://vagrantimages.blob.core.windows.net/vhds/sample.vhd"
    azure.vm_operating_system = "Linux"
  end

  config.vm.provision "shell", inline: "echo Hello, World"
end